# Generated by Django 4.1.1 on 2022-09-09 15:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reciperequirements",
            name="quantity",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="unit",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="timestamp",
            field=models.DateTimeField(
                blank=None,
                default=datetime.datetime(2022, 9, 9, 18, 37, 5, 574363),
                null=None,
            ),
        ),
        migrations.AlterField(
            model_name="reciperequirements",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.ingredient"
            ),
        ),
    ]
